### ISSUE TITLE
Using Stripe: Submit not prevented when emails do not match

### ISSUE THREAD

**Issue by insaner** [twomice/com.joineryhq.emaildouble#4]
On Backdrop / CiviCRM 5.41. CiviContribute using Stripe payment processing. Sweet Alert 1.5 extension enabled.

If I leave the "Repeat email address to confirm" field blank, the JS check prevents submission of the form due to "Missing required field" -- as expected.

But, if I enter another string in the field, like just the letter "x" it creates a red text warning ("Email addresses do not match", which I can see because of the delay in doing the payment processing), but the form data is still submitted and gives no error and the rest of the form processes successfully.

**Comment by twomice** [comment]
Thanks for reporting, finally had a chance to look at this. It's definitely related to Stripe, which (for its own good reasons) hijacks the form submit process. I've not created a fix for this yet; just letting you know it's on my radar.

**Comment by twomice** [comment]
Fixed in v1.2.0. Thanks for the report @insaner !
